const favoritesActionTypes = {
    TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
    GET_FAVORITES_WEATHER_START: 'GET_FAVORITES_WEATHER_START',
    GET_FAVORITES_WEATHER_SUCCESS: 'GET_FAVORITES_WEATHER_SUCCESS',
    GET_FAVORITES_WEATHER_FAILED: 'GET_FAVORITES_WEATHER_FAILED'
}

export default favoritesActionTypes;