const homeActionTypes = {
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
    REQUEST_SEARCH_START: 'REQUEST_SEARCH_START',
    REQUEST_SEARCH_SUCCESS: 'REQUEST_SEARCH_SUCCESS',
    REQUEST_SEARCH_FAILED: 'REQUEST_SEARCH_FAILED',
    REQUEST_FORCAST_START: 'REQUEST_FORCAST_START',
    REQUEST_FORCAST_SUCCESS: 'REQUEST_FORCAST_SUCCESS',
    REQUEST_FORCAST_FAILED: 'REQUEST_FORCAST_FAILED'
}

export default homeActionTypes;

